### ISSUE TITLE
请问如何使用改模板？

### ISSUE THREAD

**Issue by Shawdox** [zmrenwu/django-blog-tutorial-templates#3]
您好！我正在尝试使用基于django的前端模板，但不知道如何将其融入项目中，请问该如何使用该模板呢？

**Comment by SISHIDADAO0516** [comment]
I Don't know the language very well, so I'm sorry I can't help you.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月22日(周四) 上午10:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jukanntenn/django-blog-tutorial-templates] 请问如何使用改模板？ (#3)




 
您好！我正在尝试使用基于django的前端模板，但不知道如何将其融入项目中，请问该如何使用该模板呢？
